version: '3.8'

services:

  my_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - 8080
    deploy:
      replicas: 4 
      
    environment:
      - PING_LISTEN_PORT=8080
    networks:
      - front-network

    volumes:
      - db_data:/app/bdd.db

  proxy:

    container_name: my-proxy
    image: nginx:latest

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    ports:
      - 8080:80

    depends_on:
      - my_app
    networks:
      - front-network

networks:
  front-network:
    driver: bridge

volumes:
  db_data:
